title: Sasahara Lab
position: Research Internship Program
affiliation: Computational Social Science at Tokyo Insititute of Technology
email: https://www.colorlessgreen.info/home
keywords: minimal academic
google_scholar: https://scholar.google.com/
github_link: https://github.com/TokyoTech-SasaharaLAB-CREST
Web: https://www.colorlessgreen.info/contact
avatar: ./assets/img/facebook_profile_image.png
google_analytics: UA-111540567-4
favicon: ./assets/img/favicon.png
favicon_dark: ./assets/img/favicon.png
description: Computational Social Science at Sasahara Lab, Tokyo Insititute of Technology
canonical: https://github.com/TokyoTech-SasaharaLAB-CREST
remote_theme: yaoyao-liu/minimal-light
